"""Emit an Alembic baseline that adopts a database Prisma already created.

This automates §3 of `docs/prisma-to-sqlalchemy-runbook.md`, which is otherwise
`alembic init`, hand-editing `env.py`, running `alembic revision --autogenerate`
and hoping the diff comes back empty.

The cutover case, not the greenfield one
----------------------------------------

The tables exist. Prisma made them. Alembic has to take ownership without
recreating anything, so the initial revision creates nothing: it records that
this database is at the baseline. What it *does* do is refuse to do that to a
database where the tables are missing --- stamping an empty database as
already-migrated is silent, and every later migration then fails against a
schema that was never built.

What the autogenerate check is worth
------------------------------------

The runbook's gate for this phase is an empty `alembic revision --autogenerate`
diff, and the emitted `env.py` repeats, in a comment the reader cannot miss, that
this is a **weaker** check than DDL equality. Autogenerate does not compare
foreign key actions, constraint names, index methods, column order, server
defaults or sequences --- and the last two are the ones that bite: a column that
lost its `DEFAULT nextval(...)` produces an empty diff and then rejects every
INSERT. `compare_type` is switched on in the emitted config, and
`compare_server_default` is switched on with a comparison function of its own ---
Alembic reflects a non-primary-key `@default(autoincrement())` as a SERIAL and
drops its `DEFAULT nextval(...)`, which compared naively is a permanent spurious
diff *and* burns a sequence value on every autogenerate run. See
`compare_server_default` in the emitted `env.py` for what it does and does not
suppress. The stronger check --- building a second database and diffing
`pg_dump` --- is spelled out beside it.

Nothing here imports Alembic. It renders text, so it runs wherever the client
does and adds no dependency; the generated project is what needs Alembic.
"""

from __future__ import annotations

import hashlib
from typing import Any, Dict, Mapping, Optional, Sequence, NamedTuple

from ._build import build_metadata

__all__ = ('AlembicBaseline', 'build_alembic_baseline', 'PRISMA_MIGRATIONS_TABLE')

#: Prisma's own migration history. It is not in the metadata, so autogenerate
#: proposes to drop it --- and it is the history the transition still needs.
PRISMA_MIGRATIONS_TABLE = '_prisma_migrations'


class AlembicBaseline(NamedTuple):
    #: the revision identifier, derived from the schema so regenerating is a
    #: no-op rather than a second baseline
    revision: str
    #: relative path -> file contents, ready to write into a project
    files: Dict[str, str]
    #: the tables the baseline expects to find already built
    tables: Sequence[str]


def build_alembic_baseline(
    schema: Mapping[str, Any],
    enums: Mapping[str, Any],
    provider: str,
    *,
    script_location: str = 'migrations',
    models_import: Optional[str] = None,
    message: str = 'baseline: adopt the schema Prisma created',
) -> AlembicBaseline:
    """Render an Alembic project that adopts the existing Prisma schema.

    `models_import` names the module holding generated declarative models, e.g.
    `myapp.models`; leave it unset to point `env.py` at `prisma.sa.metadata()`
    instead. Either way `target_metadata` describes the same database --- that
    equivalence is what `tests/test_sqlalchemy/test_declarative.py` asserts.
    """
    metadata = build_metadata(schema, enums, provider)
    tables = sorted(table.name for table in metadata.tables.values())
    revision = _revision_id(tables)

    if models_import is None:
        import_line, expression = 'from prisma import sa', 'sa.metadata()'
    else:
        import_line, expression = f'from {models_import} import Base', 'Base.metadata'

    return AlembicBaseline(
        revision=revision,
        tables=tables,
        files={
            'alembic.ini': _alembic_ini(script_location),
            f'{script_location}/env.py': _env_py(import_line, expression),
            f'{script_location}/script.py.mako': _SCRIPT_MAKO,
            f'{script_location}/versions/{revision}_baseline.py': _baseline_revision(revision, message, tables),
        },
    )


def _revision_id(tables: Sequence[str]) -> str:
    """A revision id derived from the schema, not from the clock.

    Regenerating then overwrites the same file instead of adding a second
    baseline that neither revision knows about.
    """
    digest = hashlib.sha256('\n'.join(tables).encode('utf-8')).hexdigest()
    return digest[:12]


def _alembic_ini(script_location: str) -> str:
    return f"""# Generated by `prisma.sa`.
#
# `sqlalchemy.url` is deliberately empty: env.py reads DATABASE_URL, which is
# the variable the Prisma schema already points at, so there is one place the
# connection string lives rather than two that can disagree.
[alembic]
script_location = {script_location}
prepend_sys_path = .
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""


def _env_py(import_line: str, expression: str) -> str:
    return f'''"""Alembic environment, generated by `prisma.sa`.

The database this points at was built by Prisma. Alembic adopts it at the
baseline revision and owns DDL from then on.

**Do not run `prisma migrate` and `alembic upgrade` against the same database.**
`{PRISMA_MIGRATIONS_TABLE}` and `alembic_version` are independent and neither
knows about the other.
"""

from __future__ import annotations

import os
import re
from typing import Any, Optional

from alembic import context
from sqlalchemy import pool, engine_from_config

{import_line}

target_metadata = {expression}

config = context.config


def database_url() -> str:
    """The URL to migrate, from the environment or from alembic.ini.

    A bare `postgresql://` URL selects psycopg2. If the project uses psycopg 3 ---
    the driver `prisma.sa`'s own tests run against --- spell it
    `postgresql+psycopg://`, or SQLAlchemy fails on an import of a driver that
    was never installed.
    """
    url = os.environ.get('DATABASE_URL') or config.get_main_option('sqlalchemy.url')
    if not url:
        raise RuntimeError('Set DATABASE_URL, or sqlalchemy.url in alembic.ini, before running Alembic.')
    return url


def include_object(
    _object: Any,
    name: Optional[str],
    type_: str,
    _reflected: bool,
    _compare_to: Any,
) -> bool:
    """Leave Prisma's own bookkeeping alone.

    Alembic passes `(object, name, type_, reflected, compare_to)` positionally;
    the ones this does not read are underscored so an unused-argument lint in
    the project this lands in stays quiet.

    `{PRISMA_MIGRATIONS_TABLE}` is not in the metadata, so autogenerate would
    otherwise propose `DROP TABLE {PRISMA_MIGRATIONS_TABLE}` --- and that table is
    the Prisma migration history the transition still needs.
    """
    return not (type_ == 'table' and name == {PRISMA_MIGRATIONS_TABLE!r})


#: `nextval('"Ticket_seq"'::regclass)`, with or without the cast
NEXTVAL = re.compile(r"nextval\\('(?P<sequence>.+?)'(::regclass)?\\)\\s*$")


def compare_server_default(
    _context: Any,
    inspected_column: Any,
    _metadata_column: Any,
    inspected_default: Optional[str],
    _metadata_default: Any,
    rendered_metadata_default: Optional[str],
) -> Optional[bool]:
    """Compare `DEFAULT` clauses, without the false positive on owned sequences.

    A non-primary-key `@default(autoincrement())` carries an explicit
    `DEFAULT nextval(...)` plus `ALTER SEQUENCE ... OWNED BY` --- SQLAlchemy
    emits SERIAL only for an integer *primary* key, so without both the column
    lands NOT NULL with nothing to fill it. Alembic reflects that pair as a
    SERIAL and drops the default from the reflected column entirely, reporting
    `autoincrement` in its place. Compared naively that is a permanent, spurious
    `alter_column` on every autogenerate run --- and Alembic resolves it by
    asking the server whether the two expressions are equal, which evaluates
    `nextval()` twice, gets two different numbers, and burns a sequence value
    each time.

    What must NOT be swallowed is the real failure this comparison exists to
    catch: a column that genuinely lost its `DEFAULT nextval(...)`, which then
    rejects every INSERT. That one reflects with `autoincrement` False, so it
    still comes back as a difference.

    Returning `None` anywhere else hands the comparison back to Alembic
    unchanged.
    """
    wanted = NEXTVAL.match((rendered_metadata_default or '').strip())
    if wanted is None:
        return None

    found = NEXTVAL.match((inspected_default or '').strip())
    if found is not None:
        return found.group('sequence') != wanted.group('sequence')
    return inspected_column.autoincrement is not True


# `compare_type` and `compare_server_default` are both off by default, and the
# second is the one that bites: a column that lost its `DEFAULT nextval(...)`
# produces an *empty* diff and then rejects every INSERT.
#
# Even with both on, an empty autogenerate diff is a WEAKER check than DDL
# equality. Autogenerate does not compare:
#
#   * foreign key `ondelete` / `onupdate` actions
#   * constraint and index names
#   * index methods (`USING gin`) or per-column sort order
#   * column order
#   * server defaults, unless `compare_server_default` is set (it is, to the
#     function above, which suppresses only the owned-sequence false positive)
#   * sequences
#
# For the stronger check, build a scratch database from the same metadata this
# file points at, and diff the two schemas directly:
#
#   python -c "import sqlalchemy; {import_line}; \\
#       {expression}.create_all(sqlalchemy.create_engine('$SCRATCH'))"
#   pg_dump --schema-only --no-owner --no-acl "$PRODUCTION" > /tmp/a.sql
#   pg_dump --schema-only --no-owner --no-acl "$SCRATCH"    > /tmp/b.sql
#   diff /tmp/a.sql /tmp/b.sql
def run_migrations_offline() -> None:
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        include_object=include_object,
        compare_type=True,
        compare_server_default=compare_server_default,
        literal_binds=True,
        dialect_opts={{'paramstyle': 'named'}},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section) or {{}}
    section['sqlalchemy.url'] = database_url()
    connectable = engine_from_config(section, prefix='sqlalchemy.', poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            compare_server_default=compare_server_default,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


_SCRIPT_MAKO = '''"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''


def _baseline_revision(revision: str, message: str, tables: Sequence[str]) -> str:
    listed = '\n'.join(f'    {table!r},' for table in tables)
    return f'''"""{message}

Revision ID: {revision}
Revises:
Create Date: derived from the schema, not the clock --- see prisma.sa._alembic

This revision creates nothing. The tables already exist: Prisma built them, and
this records that the database is at the baseline so later revisions have
somewhere to start.

It is deliberately not a bare `pass`. Applying an empty baseline to a database
that was never built stamps it as migrated, silently, and every later revision
then runs against a schema that is not there --- so `upgrade()` checks first and
refuses.

Generated by `prisma.sa`. The revision id is derived from the schema, so
regenerating rewrites this file rather than adding a second baseline.
"""

from __future__ import annotations

from typing import Union, Sequence

import sqlalchemy as sa
from alembic import op

revision: str = {revision!r}
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: every table the metadata describes, including the implicit many-to-many join
#: tables Prisma manages without a model
EXPECTED_TABLES: Sequence[str] = (
{listed}
)


def upgrade() -> None:
    """Adopt the existing schema. Creates nothing; verifies it is there."""
    inspector = sa.inspect(op.get_bind())
    present = set(inspector.get_table_names())
    missing = [table for table in EXPECTED_TABLES if table not in present]
    if missing:
        raise RuntimeError(
            'This baseline adopts a database Prisma already created, and these tables\\n'
            'are not in it: ' + ', '.join(missing) + '.\\n'
            '  Point Alembic at the Prisma-managed database, or --- for a database that\\n'
            '  really is empty --- create the schema first with `MetaData.create_all()`\\n'
            '  or `prisma db push`, then run this again.\\n'
            '  Stamping an empty database as migrated is silent, and every later\\n'
            '  revision would then run against a schema that was never built.'
        )


def downgrade() -> None:
    """Un-adopt. Dropping the schema here would destroy the database Prisma built."""
'''
