"""Find Prisma call sites in Python source, with `ast`.

Why not the runbook's greps
---------------------------

§1 of the migration runbook inventories a codebase with `grep -rnE
'\\.(find_unique|find_first|...)\\('`. That is the right first move for a human
and the wrong design for a tool. A grep:

* matches the same text inside a docstring, a comment or a SQL string, so the
  count it reports is larger than the codebase's;
* keys on the *name* the client happens to be bound to, so `db.user.find_many`
  is found and `connection.user.find_many` is not;
* cannot see the arguments, and half of the runbook's §5 STOP list is about
  arguments — `update(data={'n': {'increment': 1}})` is an atomic operation, and
  its method name is on the verified list.

So this module parses. It finds all three entry syntaxes:

* ``<client>.<model>.<action>(...)``, where ``<client>`` is resolved from its
  binding (``Prisma()``, ``get_client()``, a ``Prisma`` annotation, a
  ``tx()``/``batch_()`` handle) rather than assumed to be spelled ``db``;
* ``Model.prisma().<action>(...)``;
* ``<client>.tx()`` and ``<client>.batch_()``.

What it deliberately does *not* do is decide whether a call site is migratable.
That is `_doctor`'s job, and it needs the argument nodes this module hands it.

Honesty rules
-------------

Two rules, both about not overstating what was seen:

* A receiver that could not be resolved to a client is still recorded, marked
  ``unresolved``, as long as the action name is one only Prisma has. Dropping it
  would make the report read as more complete than it is. Actions whose names
  collide with the standard library (``update``, ``count``, ``create``,
  ``delete``, ``aggregate``, ``tx``) are the exception: recording every
  ``dict.update()`` would drown the report in false positives, so those need a
  resolved or conventionally-named client.
* ``getattr(db, name).find_many()`` is recorded as ``dynamic``. The model is not
  knowable, and neither is the translation.

And one about not overstating what is *connected*: a call site belongs to a
``tx()`` block when it runs through the handle that block bound, not when it
merely sits inside the ``with``. `async with db.tx() as tx:` leaves `db` exactly
as it was, so a `db.user.count()` written in the body is a different connection
— and the doctor turns a block's members into STOPs when one of them is blocked,
so getting membership wrong would report clean call sites as blocked.
"""

from __future__ import annotations

import ast
from typing import Set, Dict, List, Tuple, Union, Mapping, Optional, Sequence, FrozenSet
from pathlib import Path
from dataclasses import field, dataclass
from typing_extensions import override

__all__ = (
    'CallSite',
    'ScanResult',
    'UnparsedFile',
    'scan_source',
    'scan_paths',
    'ACTIONS',
    'POSITIONAL_PARAMETERS',
    'render',
)

#: Model-level actions the generated client exposes.
MODEL_ACTIONS: FrozenSet[str] = frozenset(
    {
        'find_unique',
        'find_unique_or_raise',
        'find_first',
        'find_first_or_raise',
        'find_many',
        'create',
        'create_many',
        'update',
        'update_many',
        'upsert',
        'delete',
        'delete_many',
        'count',
        'group_by',
        # not generated by `prisma-client-py` today, but it is on the runbook's
        # STOP list and a codebase migrating *to* this fork may still call it
        'aggregate',
    }
)

#: Actions that live on the client itself, not on a model.
RAW_ACTIONS: FrozenSet[str] = frozenset({'query_raw', 'query_first', 'execute_raw'})

#: The transaction entry syntaxes.
TRANSACTION_ACTIONS: FrozenSet[str] = frozenset({'tx', 'batch_'})

ACTIONS: FrozenSet[str] = MODEL_ACTIONS | RAW_ACTIONS | TRANSACTION_ACTIONS

#: Action names that also name common standard-library methods. Recording one of
#: these on an unresolved receiver would flag every `dict.update()` in the
#: codebase, so they require a client we can point at.
AMBIGUOUS_ACTIONS: FrozenSet[str] = frozenset({'create', 'update', 'delete', 'count', 'aggregate', 'tx'})

#: Names a client is conventionally bound to. Matching one of these is a weaker
#: claim than resolving a binding, and is reported as such.
CONVENTIONAL_CLIENTS: FrozenSet[str] = frozenset(
    {
        'db',
        'client',
        'prisma',
        'tx',
        'transaction',
        'batcher',
        'self.db',
        'self.client',
        'self.prisma',
        'self._db',
        'self._client',
        'self._prisma',
    }
)

#: Callables that return a client.
CLIENT_FACTORIES: FrozenSet[str] = frozenset({'Prisma', 'Client', 'get_client'})

#: Annotations that mean "this is a client".
CLIENT_ANNOTATIONS: FrozenSet[str] = frozenset({'Prisma', 'Client', 'prisma.Prisma', 'prisma.Client'})

#: Methods that hand back something you can run model actions on.
_HANDLE_METHODS: FrozenSet[str] = frozenset({'tx', 'batch_', 'start'})

#: The positional parameters of each action, in order, as the generated client
#: declares them. `update(data, where)` and `upsert(where, data)` disagree, so a
#: scanner that assumed one order would mis-read the other.
POSITIONAL_PARAMETERS: Mapping[str, Sequence[str]] = {
    'find_unique': ('where', 'include'),
    'find_unique_or_raise': ('where', 'include'),
    'find_first': ('skip', 'where', 'cursor', 'include', 'order', 'distinct'),
    'find_first_or_raise': ('skip', 'where', 'cursor', 'include', 'order', 'distinct'),
    'find_many': ('take', 'skip', 'where', 'cursor', 'include', 'order', 'distinct'),
    'create': ('data', 'include'),
    'create_many': ('data',),
    'update': ('data', 'where', 'include'),
    'update_many': ('data', 'where'),
    'upsert': ('where', 'data', 'include'),
    'delete': ('where', 'include'),
    'delete_many': ('where',),
    'count': ('select', 'take', 'skip', 'where', 'cursor', 'distinct'),
    'group_by': ('by',),
    'aggregate': (),
    'query_raw': ('query',),
    'query_first': ('query',),
    'execute_raw': ('query',),
    'tx': (),
    'batch_': (),
}

#: Directories never worth walking. `site-packages` is here because a virtualenv
#: inside the tree would otherwise contribute a generated client's own source.
EXCLUDED_DIRECTORIES: FrozenSet[str] = frozenset(
    {
        '.git',
        '.hg',
        '.svn',
        '.mypy_cache',
        '.pytest_cache',
        '.ruff_cache',
        '.tox',
        '.nox',
        '.venv',
        '__pycache__',
        'build',
        'dist',
        'env',
        'node_modules',
        'site-packages',
        'venv',
    }
)


@dataclass
class CallSite:
    """One Prisma call, as parsed."""

    path: str
    line: int
    column: int
    #: ``client`` for ``db.user.find_many()`` and ``db.query_raw()``, ``model``
    #: for ``User.prisma().find_many()``, ``transaction`` for ``tx``/``batch_``.
    entry: str
    action: str
    #: the receiver as written, e.g. ``db.user`` or ``User.prisma()``
    receiver: str
    #: the client attribute (``user``) or the model class (``User``); ``None``
    #: for client-level and dynamic call sites
    model: Optional[str]
    #: ``binding`` (resolved from an assignment or annotation), ``convention``
    #: (matched a conventional client name only), ``unresolved`` or ``dynamic``
    resolution: str
    #: argument name -> the expression node, positional arguments named
    arguments: Dict[str, ast.expr] = field(default_factory=dict)
    #: ``*`` and/or ``**`` when the call splats arguments we cannot see
    opaque_arguments: List[str] = field(default_factory=list)
    #: id of the innermost enclosing ``tx()``/``batch_()`` ``with`` block
    block: Optional[str] = None


@dataclass
class UnparsedFile:
    path: str
    error: str


@dataclass
class ScanResult:
    call_sites: List[CallSite] = field(default_factory=list)
    files_scanned: int = 0
    unparsed: List[UnparsedFile] = field(default_factory=list)

    def extend(self, other: 'ScanResult') -> None:
        self.call_sites.extend(other.call_sites)
        self.files_scanned += other.files_scanned
        self.unparsed.extend(other.unparsed)


def render(node: ast.AST) -> str:
    """A short source-ish rendering of an expression.

    `ast.unparse` would do this, and arrived in 3.9; this library supports 3.8.
    The output is for a human reading the report, so an unrecognised node
    rendering as `...` costs nothing.
    """
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f'{render(node.value)}.{node.attr}'
    if isinstance(node, ast.Call):
        return '{}({})'.format(render(node.func), ', '.join(render(argument) for argument in node.args))
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.Subscript):
        return f'{render(node.value)}[...]'
    if isinstance(node, ast.Await):
        return f'await {render(node.value)}'
    if isinstance(node, ast.Starred):
        return f'*{render(node.value)}'
    if isinstance(node, ast.Dict):
        return '{...}'
    if isinstance(node, (ast.List, ast.Tuple)):
        return '[...]'
    return '...'


def mapping_items(node: ast.expr) -> Optional[List[Tuple[Optional[str], ast.expr]]]:
    """`[(key, value)]` for a dict literal, or `None` when it is not one.

    A key that is not a string constant comes back as `None`, which the caller
    must treat as "could be anything" rather than skipping.
    """
    if not isinstance(node, ast.Dict):
        return None

    items: List[Tuple[Optional[str], ast.expr]] = []
    for key, value in zip(node.keys, node.values):
        if isinstance(key, ast.Constant) and isinstance(key.value, str):
            items.append((key.value, value))
        else:
            # `**other` inside a literal gives a `None` key, as does a computed one
            items.append((None, value))
    return items


def sequence_items(node: ast.expr) -> Optional[List[ast.expr]]:
    """The elements of a list/tuple literal, or `None`."""
    if isinstance(node, (ast.List, ast.Tuple)):
        if any(isinstance(element, ast.Starred) for element in node.elts):
            return None
        return list(node.elts)
    return None


def same_expression(left: ast.expr, right: ast.expr) -> bool:
    """Whether two expressions are written identically.

    Positions are excluded, so `1` on two different lines compares equal. This
    is deliberately syntactic: it answers "did the author write the same thing
    here as there", which is exactly what the `upsert` precondition asks.
    """
    return ast.dump(left) == ast.dump(right)


def scan_source(source: str, path: str) -> ScanResult:
    """Scan one module's source text."""
    result = ScanResult()
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        result.unparsed.append(UnparsedFile(path=path, error=str(exc)))
        return result

    result.files_scanned = 1
    visitor = _Visitor(path=path, bindings=_client_bindings(tree))
    visitor.visit(tree)
    result.call_sites.extend(visitor.call_sites)
    return result


def scan_paths(paths: Sequence[Path], *, root: Path) -> ScanResult:
    """Scan every `.py` file under `paths`, reporting names relative to `root`."""
    result = ScanResult()

    for file in _python_files(paths):
        name = _relative(file, root)
        try:
            source = file.read_text(encoding='utf-8')
        except (UnicodeDecodeError, OSError) as exc:
            result.unparsed.append(UnparsedFile(path=name, error=str(exc)))
            continue

        result.extend(scan_source(source, name))

    return result


def _relative(file: Path, root: Path) -> str:
    try:
        return file.relative_to(root).as_posix()
    except ValueError:
        return file.as_posix()


def _python_files(paths: Sequence[Path]) -> List[Path]:
    found: List[Path] = []
    seen: Set[Path] = set()

    for path in paths:
        if path.is_dir():
            candidates = sorted(path.rglob('*.py'))
        else:
            candidates = [path]

        for candidate in candidates:
            if EXCLUDED_DIRECTORIES.intersection(candidate.parts):
                continue
            resolved = candidate.absolute()
            if resolved in seen:
                continue
            seen.add(resolved)
            found.append(candidate)

    return found


def _client_bindings(tree: ast.AST) -> Set[str]:
    """Every name in this module that holds a Prisma client.

    A whole-module pass, not an in-order one: a client assigned at the bottom of
    a module is still the client the functions above it use.
    """
    factories: Set[str] = set(CLIENT_FACTORIES)
    annotations: Set[str] = set(CLIENT_ANNOTATIONS)

    # `from prisma import Prisma as PrismaClient` — the aliased-client case a
    # grep cannot follow at all.
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and (node.module or '').split('.')[0] == 'prisma':
            for alias in node.names:
                if alias.name in CLIENT_FACTORIES:
                    factories.add(alias.asname or alias.name)
                    annotations.add(alias.asname or alias.name)

    bindings: Set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            if _is_client_expression(node.value, factories):
                for target in node.targets:
                    _bind(bindings, target)
        elif isinstance(node, ast.AnnAssign):
            if _annotation_name(node.annotation) in annotations:
                _bind(bindings, node.target)
            elif node.value is not None and _is_client_expression(node.value, factories):
                _bind(bindings, node.target)
        elif isinstance(node, ast.arg):
            if node.annotation is not None and _annotation_name(node.annotation) in annotations:
                bindings.add(node.arg)
        elif isinstance(node, ast.withitem):
            if node.optional_vars is not None and _opens_transaction(node.context_expr):
                _bind(bindings, node.optional_vars)

    return bindings


def _bind(bindings: Set[str], target: ast.expr) -> None:
    if isinstance(target, (ast.Name, ast.Attribute)):
        bindings.add(render(target))


def _annotation_name(node: ast.expr) -> str:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        # a string annotation, e.g. `def handler(db: 'Prisma')`
        return node.value
    return render(node)


def _is_client_expression(node: ast.expr, factories: Set[str]) -> bool:
    """Whether an expression evaluates to something you can run actions on."""
    if isinstance(node, ast.Await):
        return _is_client_expression(node.value, factories)
    if not isinstance(node, ast.Call):
        return False
    if isinstance(node.func, ast.Name):
        return node.func.id in factories
    if isinstance(node.func, ast.Attribute):
        # `prisma.Prisma()`, and the handles `db.tx()` / `db.batch_()` /
        # `db.tx().start()` hand back
        return node.func.attr in factories or node.func.attr in _HANDLE_METHODS
    return False


def _opens_transaction(node: ast.expr) -> bool:
    return isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr in TRANSACTION_ACTIONS


class _Visitor(ast.NodeVisitor):
    def __init__(self, path: str, bindings: Set[str]) -> None:
        self.path = path
        self.bindings = bindings
        self.call_sites: List[CallSite] = []
        #: (block id, the name the block's handle is bound to)
        self._blocks: List[Tuple[str, Optional[str]]] = []
        #: set while visiting the expression that opens a block, so the
        #: `tx()`/`batch_()` call itself belongs to the block it opens
        self._opening: Optional[str] = None

    # `with` and `async with` are where a transaction's body is delimited. The
    # runbook is explicit that a `tx()` block migrates whole or not at all, so
    # the doctor needs to know which call sites are inside which block.
    @override
    def visit_With(self, node: ast.With) -> None:
        self._visit_with(node)

    @override
    def visit_AsyncWith(self, node: ast.AsyncWith) -> None:
        self._visit_with(node)

    def _visit_with(self, node: Union[ast.With, ast.AsyncWith]) -> None:
        opened = 0
        for item in node.items:
            kind = self._transaction_kind(item.context_expr)
            if kind is None:
                self.visit(item.context_expr)
                continue

            block = f'{kind}@{self.path}:{item.context_expr.lineno}'
            self._opening = block
            self.visit(item.context_expr)
            self._opening = None

            bound = item.optional_vars
            self._blocks.append((block, render(bound) if bound is not None else None))
            opened += 1

        for statement in node.body:
            self.visit(statement)

        for _ in range(opened):
            self._blocks.pop()

    def _block_for(self, handles: Sequence[str]) -> Optional[str]:
        """The innermost open block this call actually runs through.

        Lexical nesting is not enough. `async with db.tx() as tx:` makes `tx`
        transactional and leaves `db` exactly as it was, so a `db.user.count()`
        written inside the block is a *different* connection — attributing it to
        the block would report a verified call site as blocked. The block's
        members are the calls that go through the handle it bound.
        """
        if self._opening is not None:
            return self._opening

        for block, bound in reversed(self._blocks):
            if bound is not None and bound in handles:
                return block
        return None

    def _transaction_kind(self, node: ast.expr) -> Optional[str]:
        if not _opens_transaction(node):
            return None
        assert isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
        if self._record_transaction(node.func.attr, node.func.value) is None:
            return None
        return node.func.attr

    def _record_transaction(self, action: str, receiver: ast.expr) -> Optional[str]:
        """The resolution for a transaction opened on `receiver`, or `None`."""
        resolution = self._resolve(receiver)
        if resolution == 'unresolved' and action in AMBIGUOUS_ACTIONS:
            return None
        return resolution

    @override
    def visit_Call(self, node: ast.Call) -> None:
        site = self._call_site(node)
        if site is not None:
            self.call_sites.append(site)
        self.generic_visit(node)

    def _call_site(self, node: ast.Call) -> Optional[CallSite]:
        if not isinstance(node.func, ast.Attribute):
            return None

        action = node.func.attr
        if action not in ACTIONS:
            return None

        base = node.func.value
        made = self._entry(action, base)
        if made is None:
            return None

        entry, model, resolution, receiver, handles = made
        arguments, opaque = _arguments(node, action)
        return CallSite(
            path=self.path,
            line=node.lineno,
            column=node.col_offset,
            entry=entry,
            action=action,
            receiver=receiver,
            model=model,
            resolution=resolution,
            arguments=arguments,
            opaque_arguments=opaque,
            block=self._block_for(handles),
        )

    def _entry(self, action: str, base: ast.expr) -> Optional[Tuple[str, Optional[str], str, str, List[str]]]:
        """`(entry, model, resolution, receiver, handles)`, or None.

        `handles` are the names this call runs through — the client, or the
        transaction handle passed to `Model.prisma(tx)` — and are what decide
        which transaction block, if any, the call belongs to.
        """
        if action in TRANSACTION_ACTIONS:
            resolution = self._record_transaction(action, base)
            if resolution is None:
                return None
            return ('transaction', None, resolution, render(base), [render(base)])

        # `Model.prisma().action(...)`
        if _is_prisma_accessor(base):
            assert isinstance(base, ast.Call)
            # `Model.prisma(tx)` is how the second entry syntax joins a
            # transaction; without reading the argument the call looks like it
            # belongs to no block at all.
            handles = [render(argument) for argument in base.args]
            handles += [render(keyword.value) for keyword in base.keywords]
            model = _model_accessor(base)
            if model is None:
                # `registry['User'].prisma()` — the model is chosen at runtime.
                # Recording it as dynamic keeps it in the count; dropping it
                # would make the report read as more complete than it is.
                return ('model', None, 'dynamic', render(base), handles)
            return ('model', model, 'binding', render(base), handles)

        # `getattr(db, name).action(...)` — the model is not knowable
        if isinstance(base, ast.Call) and isinstance(base.func, ast.Name) and base.func.id == 'getattr':
            if not base.args or self._resolve(base.args[0]) == 'unresolved':
                return None
            return ('client', None, 'dynamic', render(base), [render(base.args[0])])

        # `db.query_raw(...)` — an action on the client itself
        if action in RAW_ACTIONS:
            resolution = self._resolve(base)
            if resolution != 'unresolved':
                return ('client', None, resolution, render(base), [render(base)])

        # `db.user.action(...)`
        if isinstance(base, ast.Attribute):
            resolution = self._resolve(base.value)
            if resolution == 'unresolved' and action in AMBIGUOUS_ACTIONS:
                return None
            return ('client', base.attr, resolution, render(base), [render(base.value)])

        return None

    def _resolve(self, node: ast.expr) -> str:
        rendered = render(node)
        if rendered in self.bindings:
            return 'binding'
        if rendered in CONVENTIONAL_CLIENTS:
            return 'convention'
        return 'unresolved'


def _is_prisma_accessor(node: ast.expr) -> bool:
    """Any `<something>.prisma()`, resolvable to a model or not."""
    return isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == 'prisma'


def _model_accessor(node: ast.expr) -> Optional[str]:
    """The model name behind `Model.prisma()`, the second entry syntax.

    `models.User.prisma()` counts: `from prisma import models` and then reaching
    through the module is as common as importing the class, and a check that
    insisted on a bare `Name` would drop every call site written that way.
    """
    if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
        return None
    if node.func.attr != 'prisma':
        return None

    owner = node.func.value
    if isinstance(owner, ast.Name):
        name = owner.id
    elif isinstance(owner, ast.Attribute):
        name = owner.attr
    else:
        return None

    return name if name[:1].isupper() else None


def _arguments(node: ast.Call, action: str) -> Tuple[Dict[str, ast.expr], List[str]]:
    positional = POSITIONAL_PARAMETERS.get(action, ())
    arguments: Dict[str, ast.expr] = {}
    opaque: List[str] = []

    for index, argument in enumerate(node.args):
        if isinstance(argument, ast.Starred) or index >= len(positional):
            if '*' not in opaque:
                opaque.append('*')
            continue
        arguments[positional[index]] = argument

    for keyword in node.keywords:
        if keyword.arg is None:
            if '**' not in opaque:
                opaque.append('**')
            continue
        arguments[keyword.arg] = keyword.value

    return arguments, opaque
