"""The values Prisma fills in on the **client**, not in the database.

Why this exists
---------------

`@default(cuid())`, `@default(uuid())`, `@default(nanoid())`, `@default(now())`
and `@updatedAt` leave no trace in the DDL Prisma emits — with one exception,
`now()`, which does get a `DEFAULT CURRENT_TIMESTAMP` the engine then never
relies on. `_build` deliberately emits nothing for the rest (see
`_CLIENT_SIDE_GENERATORS`), because inventing a server default is a schema diff
against every real database *and* hides a missing client value behind an INSERT
that appears to work.

The consequence is that a hand-written INSERT produces a row with a NULL primary
key where Prisma produces a valid one. This module is the missing half: it turns
a mapping of Prisma **field** names into a mapping of **column** names with the
client-side values filled in, so `sa.insert(table).values(**values)` lands the
row Prisma would have landed.

What was measured, and against what
-----------------------------------

Every claim below was observed from a live Prisma client (CLI 5.19.0, the pinned
version) against PostgreSQL, not recalled:

``cuid()``
    25 characters: ``c``, an 8-character base36 millisecond timestamp, a
    4-character base36 counter that increments per call within a process, a
    4-character per-process fingerprint, then 8 characters of base36 randomness.
    Observed ids: ``cmsdl22aq0000we3nbbzl0811``, ``cmsdl22b20001we3nvwijvv6a`` —
    the counter block moving ``0000`` → ``0001`` is what identifies the layout.

``uuid()`` / ``uuid(4)`` / ``uuid(7)``
    The DMMF reports the version separately (``version``), because Prisma
    normalises ``uuid()`` to ``uuid(4)`` on the wire. Version 4 is a random
    UUID; version 7 is RFC 9562's time-ordered one — observed values carry a
    48-bit millisecond timestamp and sort by creation time. Emitted as `str`,
    which binds to both a `text` column and a `@db.Uuid` one.

``nanoid()`` / ``nanoid(n)``
    21 characters by default, ``n`` when given. The alphabet was recovered from
    3000 engine-generated values and is exactly these 64 characters:
    ``-``, ``0-9``, ``A-Z``, ``_``, ``a-z``.

``now()``
    **Filled here, despite having a server default.** Measured: with the column
    default replaced by a sentinel, a Prisma `create` still landed the current
    time, so the engine sends the value and the `DEFAULT CURRENT_TIMESTAMP` is
    never reached. This is not a detail — `CURRENT_TIMESTAMP` is *transaction
    start* time, so relying on it inside a transaction backdates the row and
    breaks the `createdAt == updatedAt` equality Prisma guarantees on a fresh
    row.

``@updatedAt``
    Client-side on INSERT **and** on UPDATE; measured both. The column has no
    server default at all, so an INSERT that omits it fails on NOT NULL. On
    create it gets exactly the same instant as `now()`.

``autoincrement()``
    Database-side: `SERIAL`, or the explicit sequence `_build` attaches to a
    non-primary-key column. Nothing to fill.

``ulid()``, ``auto()``, ``cuid(2)``
    Refused. The pinned CLI rejects `ulid()` and `cuid(2)` outright, so their
    output could not be observed, and `auto()` is MongoDB-only. A plausible
    guess about an id format is not a small mistake — it is silent data
    corruption discovered later.

Timestamps
----------

Two things that look cosmetic and are not:

* The value is **naive UTC** for a `timestamp without time zone` column and
  **aware UTC** for `@db.Timestamptz`. Measured: binding an aware datetime to a
  `timestamp` column converts it using the session's `TimeZone`, so under
  ``SET TIME ZONE 'America/New_York'`` a UTC value lands five hours earlier.
* It is truncated to **milliseconds**, which is the resolution of the engine's
  clock and of Prisma's `timestamp(3)` columns. Keeping microseconds makes the
  value returned here differ from the value the database stores.

One more measured detail, for anyone building bulk writes on top of this:
`create_many` gives **every row in the batch the same instant**, not one each.
Pass `moment=` to reproduce that.
"""

from __future__ import annotations

import os
import enum
import uuid as _uuid
import random
import socket
import datetime
import itertools
import threading
import collections.abc
from typing import Any, Dict, List, Mapping, Optional

from .._schema import FieldSchema, ModelSchema, enum_label, model_schema

__all__ = ('values_for_create', 'values_for_update')


class _Missing:
    """Sentinel for 'the database supplies this', distinct from `None`."""


_MISSING = _Missing()

#: Recovered from 3000 values generated by the query engine. Order is
#: irrelevant — it is a set to draw uniformly from — but the membership is not.
_NANOID_ALPHABET = '-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz'
_NANOID_DEFAULT_SIZE = 21

_BASE36 = '0123456789abcdefghijklmnopqrstuvwxyz'
_CUID_BLOCK = 4
_CUID_DISCRETE_VALUES = 36**_CUID_BLOCK

#: `@db.*` annotations a generated timestamp is verified against. `Date`, `Time`
#: and the rest are refused rather than coerced: what Prisma writes into them
#: was never observed.
_TIMESTAMP_NATIVE_TYPES = frozenset({'Timestamp', 'Timestamptz'})

_random = random.SystemRandom()
_counter = itertools.count()
_fingerprint_lock = threading.Lock()
_fingerprint: Optional[str] = None

_uuid7_lock = threading.Lock()
_uuid7_millisecond = -1
_uuid7_sequence = 0


def values_for_create(
    model: str,
    data: Mapping[str, Any],
    *,
    moment: Optional[datetime.datetime] = None,
) -> Dict[str, Any]:
    """Column-keyed values for an INSERT, with client-side defaults filled in.

    `data` is keyed by Prisma **field** name; the result is keyed by **column**
    name, with `@map` resolved and enum members mapped to their stored labels.

    Fields absent from `data` that Prisma would fill on the client — `cuid()`,
    `uuid()`, `nanoid()`, `now()`, `@updatedAt` — are added. Fields the database
    fills — `autoincrement()`, a literal default, `dbgenerated()` — are left
    out, because `_build` emits a server default for exactly those. A required
    field with no default at all is also left out: that is the caller's mistake,
    and a NOT NULL violation reports it far more clearly than a guess would.

    `moment` is the instant generated timestamps are stamped with, defaulting to
    now. Pass one instant across a batch of rows to reproduce `create_many`,
    where — measured — every row in the batch shares a single timestamp rather
    than getting its own.

    Raises `LookupError` naming the field for anything that is not a scalar or
    enum column of `model`, and `NotImplementedError` naming it for a generator
    whose output has not been verified against a real Prisma client.
    """
    spec = model_schema(model)
    values = _translate(model, spec, data)
    stamp = _normalise(moment)

    for name, field in spec['fields'].items():
        if name in data:
            continue
        generated = _client_side_value(model, name, field, stamp)
        if not isinstance(generated, _Missing):
            values[field['column']] = generated

    return values


def values_for_update(
    model: str,
    data: Mapping[str, Any],
    *,
    moment: Optional[datetime.datetime] = None,
) -> Dict[str, Any]:
    """Column-keyed values for an UPDATE, with `@updatedAt` refreshed.

    Only `@updatedAt` is added — an update does not re-run `@default(...)`, so
    no id is generated and `createdAt` is left alone. An explicit `updatedAt` in
    `data` wins, which is what Prisma does.

    `moment` is the instant to stamp, defaulting to now; see `values_for_create`.

    Atomic operations (`{'increment': 1}`) are **refused**: they are on the
    runbook's STOP list, and passing the mapping through would write the mapping.
    """
    spec = model_schema(model)
    values = _translate(model, spec, data)
    stamp = _normalise(moment)

    for name, field in spec['fields'].items():
        if name in data or not field['is_updated_at']:
            continue
        values[field['column']] = _timestamp(model, name, field, stamp)

    return values


def _translate(model: str, spec: ModelSchema, data: Mapping[str, Any]) -> Dict[str, Any]:
    """Field names -> column names, member names -> stored enum labels."""
    values: Dict[str, Any] = {}

    for name, value in data.items():
        field = spec['fields'].get(name)
        if field is None:
            if name in spec['relations']:
                raise LookupError(
                    f'{model}.{name} is a relation, not a column. Nested writes are not translated here; '
                    'write the foreign key column, or the related row first.'
                )
            raise LookupError(f'Unknown field: {model}.{name}')

        values[field['column']] = _convert(model, name, field, value)

    return values


def _convert(model: str, name: str, field: FieldSchema, value: Any) -> Any:
    if value is None:
        return None

    if isinstance(value, collections.abc.Mapping) and field['type'] != 'Json':
        raise NotImplementedError(
            f'{model}.{name} was given {dict(value)!r}. A mapping here is an atomic operation '
            f'({"/".join(sorted(str(key) for key in value))}), which has no verified translation; '
            'writing it through would store the mapping itself.'
        )

    if field['kind'] != 'enum':
        return value

    if field['is_list']:
        return [enum_label(field['type'], _member_name(item)) for item in value]

    return enum_label(field['type'], _member_name(value))


def _member_name(value: Any) -> str:
    """The Prisma member name, which is what `enum_label` maps.

    A generated client hands you a `StrEnum` whose *value* is the member name;
    `@map` lives only in the metadata, so the label never appears in Python.
    """
    if isinstance(value, enum.Enum):
        return str(value.value)
    return str(value)


def _client_side_value(model: str, name: str, field: FieldSchema, moment: datetime.datetime) -> Any:
    if field['is_updated_at']:
        return _timestamp(model, name, field, moment)

    default = field['default']
    if default is None:
        return _MISSING

    if default.get('kind') != 'generator':
        # a literal, which `_build` emits as a server default
        return _MISSING

    # `.get`, not `[...]`: `DefaultSpec` is a union of the generator and literal
    # shapes, so `name` is not a required key. The `kind` guard above establishes
    # which arm we are on, but a type checker cannot narrow a TypedDict on the
    # value of a sibling key.
    generator = default.get('name')
    version = default.get('version')
    if generator is None:
        raise NotImplementedError(f'{model}.{name} has a generator default with no name: {default!r}')

    if generator == 'cuid':
        if version not in (None, '1'):
            raise NotImplementedError(
                f'{model}.{name} uses cuid({version}), whose format has not been verified '
                f'against a real Prisma client; cuid() has'
            )
        return cuid()

    if generator == 'uuid':
        # `uuid()` reaches the DMMF as version '4'; an unversioned spec can only
        # come from a client that does not report the version at all, and
        # unversioned `uuid()` has never meant anything but v4.
        if version in (None, '4'):
            return str(_uuid.uuid4())
        if version == '7':
            return str(_uuid7())
        raise NotImplementedError(
            f'{model}.{name} uses uuid({version}); only versions 4 and 7 have been verified '
            'against a real Prisma client'
        )

    if generator == 'nanoid':
        return _nanoid(_nanoid_size(model, name, default.get('args') or []))

    if generator == 'now':
        return _timestamp(model, name, field, moment)

    if generator in ('autoincrement', 'dbgenerated'):
        # the database's job; `_build` emits the sequence or the DEFAULT clause
        return _MISSING

    if generator == 'ulid':
        raise NotImplementedError(
            f'{model}.{name} uses ulid(). The pinned Prisma CLI does not accept `@default(ulid())`, '
            'so what the engine generates for it could not be observed, and an id format is not '
            'something to guess at.'
        )

    if generator == 'auto':
        raise NotImplementedError(f'{model}.{name} uses auto(), which is MongoDB-only. `prisma.sa` is PostgreSQL-only.')

    raise NotImplementedError(f'{model}.{name} uses an unhandled Prisma default generator: {generator}()')


def _nanoid_size(model: str, name: str, args: List[Any]) -> int:
    if not args:
        return _NANOID_DEFAULT_SIZE
    try:
        size = int(args[0])
    except (TypeError, ValueError):
        raise NotImplementedError(f'{model}.{name} uses nanoid({args[0]!r}), which is not a length') from None
    if size < 1:
        raise NotImplementedError(f'{model}.{name} uses nanoid({size}), which cannot produce a value')
    return size


def _timestamp(model: str, name: str, field: FieldSchema, moment: datetime.datetime) -> datetime.datetime:
    native = field.get('native_type')
    annotation = str(native[0]) if native else None

    if annotation is not None and annotation not in _TIMESTAMP_NATIVE_TYPES:
        raise NotImplementedError(
            f'{model}.{name} is a generated timestamp on a @db.{annotation} column. What Prisma writes '
            'into that column was not observed, and a datetime coerced by the driver is a guess.'
        )

    if annotation == 'Timestamptz':
        return moment
    # `timestamp without time zone` takes the UTC wall clock. An aware value is
    # converted by the session's TimeZone on the way in, which is not UTC by
    # default everywhere.
    return moment.replace(tzinfo=None)


def _normalise(moment: Optional[datetime.datetime]) -> datetime.datetime:
    """A caller's instant, or now — either way UTC-aware and millisecond-exact.

    A naive `moment` is read as UTC. There is no second reasonable reading: the
    values here are Prisma's, and Prisma's are UTC.
    """
    if moment is None:
        moment = datetime.datetime.now(datetime.timezone.utc)
    elif moment.tzinfo is None:
        moment = moment.replace(tzinfo=datetime.timezone.utc)
    else:
        moment = moment.astimezone(datetime.timezone.utc)

    return moment.replace(microsecond=(moment.microsecond // 1000) * 1000)


def cuid() -> str:
    """A cuid of the shape the Prisma query engine generates.

    `c` + base36 milliseconds + base36 counter + per-process fingerprint +
    randomness, which is 25 characters until the timestamp needs a ninth digit
    in 2059. The blocks are not decorative: the timestamp makes ids roughly
    sortable, and the counter is what keeps two ids generated in the same
    millisecond apart.
    """
    timestamp = _base36(int(datetime.datetime.now(datetime.timezone.utc).timestamp() * 1000), 8)
    counter = _base36(next(_counter) % _CUID_DISCRETE_VALUES, _CUID_BLOCK)
    randomness = _base36(_random.randrange(_CUID_DISCRETE_VALUES**2), _CUID_BLOCK * 2)
    return f'c{timestamp}{counter}{_process_fingerprint()}{randomness}'


def _base36(value: int, width: int) -> str:
    if value == 0:
        return '0' * width

    digits = []
    while value:
        value, remainder = divmod(value, 36)
        digits.append(_BASE36[remainder])

    return ''.join(reversed(digits)).rjust(width, '0')


def _process_fingerprint() -> str:
    """Four characters that separate two processes generating ids at once.

    The same two inputs the reference implementation uses — the process id and
    the host name — because two workers on one host share a clock and a counter
    space and would otherwise collide on more than randomness.
    """
    global _fingerprint

    if _fingerprint is None:
        with _fingerprint_lock:
            if _fingerprint is None:
                pid = _base36(os.getpid(), 2)[-2:]
                host = socket.gethostname()
                host_id = _base36(sum(ord(char) for char in host) + len(host) + 36, 2)[-2:]
                _fingerprint = f'{pid}{host_id}'

    return _fingerprint


def _nanoid(size: int) -> str:
    return ''.join(_random.choice(_NANOID_ALPHABET) for _ in range(size))


def _uuid7() -> _uuid.UUID:
    """RFC 9562 version 7: a 48-bit millisecond timestamp, then randomness.

    Python's `uuid` module only grew `uuid7` in 3.14, and the point of a v7 is
    that it sorts by creation time, so falling back to a v4 would be the exact
    silent divergence this module exists to prevent.

    The 12 bits after the version hold a counter rather than randomness — RFC
    9562's "replace leftmost random bits with increased clock precision" method
    — because two ids generated in the same millisecond would otherwise sort at
    random, which is the one property a v7 is chosen for.
    """
    global _uuid7_millisecond, _uuid7_sequence

    now = int(datetime.datetime.now(datetime.timezone.utc).timestamp() * 1000)

    with _uuid7_lock:
        if now > _uuid7_millisecond:
            _uuid7_millisecond, _uuid7_sequence = now, 0
        else:
            # same millisecond, or a clock that went backwards
            _uuid7_sequence += 1
            if _uuid7_sequence > 0xFFF:
                _uuid7_millisecond += 1
                _uuid7_sequence = 0
        milliseconds, sequence = _uuid7_millisecond, _uuid7_sequence

    value = (milliseconds & 0xFFFFFFFFFFFF) << 80
    value |= 0x7 << 76  # version
    value |= sequence << 64
    value |= 0b10 << 62  # variant
    value |= _random.getrandbits(62)
    return _uuid.UUID(int=value)
